
package br.com.fiap.winery.stubclasses;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "WineWarningServiceImplementacionService", targetNamespace = "http://winery.fiap.com.br/", wsdlLocation = "http://localhost:8085/WineWarningService?wsdl")
public class WineWarningServiceImplementacionService
    extends Service
{

    private static final URL WINEWARNINGSERVICEIMPLEMENTACIONSERVICE_WSDL_LOCATION;
    private static final WebServiceException WINEWARNINGSERVICEIMPLEMENTACIONSERVICE_EXCEPTION;
    private static final QName WINEWARNINGSERVICEIMPLEMENTACIONSERVICE_QNAME = new QName("http://winery.fiap.com.br/", "WineWarningServiceImplementacionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/WineWarningService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WINEWARNINGSERVICEIMPLEMENTACIONSERVICE_WSDL_LOCATION = url;
        WINEWARNINGSERVICEIMPLEMENTACIONSERVICE_EXCEPTION = e;
    }

    public WineWarningServiceImplementacionService() {
        super(__getWsdlLocation(), WINEWARNINGSERVICEIMPLEMENTACIONSERVICE_QNAME);
    }

    public WineWarningServiceImplementacionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WINEWARNINGSERVICEIMPLEMENTACIONSERVICE_QNAME, features);
    }

    public WineWarningServiceImplementacionService(URL wsdlLocation) {
        super(wsdlLocation, WINEWARNINGSERVICEIMPLEMENTACIONSERVICE_QNAME);
    }

    public WineWarningServiceImplementacionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WINEWARNINGSERVICEIMPLEMENTACIONSERVICE_QNAME, features);
    }

    public WineWarningServiceImplementacionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WineWarningServiceImplementacionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WineWarningService
     */
    @WebEndpoint(name = "WineWarningServiceImplementacionPort")
    public WineWarningService getWineWarningServiceImplementacionPort() {
        return super.getPort(new QName("http://winery.fiap.com.br/", "WineWarningServiceImplementacionPort"), WineWarningService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WineWarningService
     */
    @WebEndpoint(name = "WineWarningServiceImplementacionPort")
    public WineWarningService getWineWarningServiceImplementacionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://winery.fiap.com.br/", "WineWarningServiceImplementacionPort"), WineWarningService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WINEWARNINGSERVICEIMPLEMENTACIONSERVICE_EXCEPTION!= null) {
            throw WINEWARNINGSERVICEIMPLEMENTACIONSERVICE_EXCEPTION;
        }
        return WINEWARNINGSERVICEIMPLEMENTACIONSERVICE_WSDL_LOCATION;
    }

}
